//! What is installed, and what is available.
//!
//! Four questions, four different authorities, and none of them is a guess:
//!
//! - **What does the gamemode call itself?** `Code/Core/BuildVersion.g.cs`,
//!   generated by AppleJackRP's `tools/stamp_version.py` from the changelog's
//!   top heading plus the git commit. It is the version the build reports
//!   in-game, so it is the one an operator will be asked about.
//! - **What commit is checked out?** `git rev-parse`, when the project is a
//!   working tree. A container image has no `.git`, and that is not a fault: the
//!   stamp above still answers.
//! - **What commit does the remote have?** `git ls-remote`, which needs no fetch
//!   and writes nothing, so it is safe to run on a timer against a checkout
//!   somebody is working in.
//! - **What build of the dedicated server is installed, and what is published?**
//!   Steam's own manifest, `steamapps/appmanifest_1892930.acf`, against
//!   `steamcmd +app_info_print`. The engine has no version endpoint a third
//!   party can call.

use std::path::{Path, PathBuf};
use std::process::Stdio;

use serde::{Deserialize, Serialize};

/// Steam app id of the s&box dedicated server.
///
/// Not 590830, which is the client. The dedicated server is a separate,
/// anonymously downloadable app.
pub const SBOX_DEDICATED_APP_ID: &str = "1892930";

/// Everything Cellar knows about what is installed and what is not.
#[derive(Debug, Clone, Default, PartialEq, Eq, Serialize, Deserialize)]
pub struct Versions {
    pub gamemode: Option<GamemodeVersion>,
    pub git: Option<GitVersion>,
    pub engine: Option<EngineVersion>,
    /// Filled when a probe could not answer, so the UI can say "unknown"
    /// distinctly from "up to date".
    pub problems: Vec<String>,
}

impl Versions {
    /// Whether anything is known to be behind.
    pub fn update_available(&self) -> bool {
        self.git.as_ref().is_some_and(GitVersion::is_behind)
            || self.engine.as_ref().is_some_and(EngineVersion::is_behind)
    }

    /// A one-line summary for a status bar.
    pub fn summary(&self) -> String {
        let gamemode = self
            .gamemode
            .as_ref()
            .map(|v| v.version.clone())
            .unwrap_or_else(|| "unknown".to_owned());

        let engine = self
            .engine
            .as_ref()
            .map(|v| v.installed_build.clone())
            .unwrap_or_else(|| "unknown".to_owned());

        if self.update_available() {
            format!("gamemode {gamemode}, engine build {engine} (update available)")
        } else {
            format!("gamemode {gamemode}, engine build {engine}")
        }
    }

    /// Compare the build stamp Cellar launched with the current `main` tip.
    pub fn build_drift(&self) -> BuildDrift {
        let running_commit = self
            .gamemode
            .as_ref()
            .map(|version| version.commit.clone())
            .filter(|commit| !commit.trim().is_empty())
            .or_else(|| self.git.as_ref().map(|git| git.head.clone()));
        let main_commit = self.git.as_ref().and_then(|git| git.remote_head.clone());

        let state = match (&running_commit, &main_commit) {
            (Some(running), Some(main)) if commits_match(running, main) => "synced",
            (Some(running), Some(main)) if !running.is_empty() && !main.is_empty() => "drifted",
            _ => "unknown",
        };

        let detail = match state {
            "synced" => "running AppleJackRP build matches origin/main",
            "drifted" => "running AppleJackRP build differs from origin/main",
            _ => "AppleJackRP build sync could not be verified",
        };

        BuildDrift {
            state: state.to_owned(),
            running_commit,
            main_commit,
            detail: detail.to_owned(),
        }
    }
}

/// Whether two full or abbreviated git object names identify the same commit.
fn commits_match(left: &str, right: &str) -> bool {
    left == right
        || (left.len() >= 7 && right.starts_with(left))
        || (right.len() >= 7 && left.starts_with(right))
}

/// The operator-facing answer to "is the live AppleJackRP build current?".
#[derive(Debug, Clone, Default, PartialEq, Eq, Serialize, Deserialize)]
pub struct BuildDrift {
    pub state: String,
    pub running_commit: Option<String>,
    pub main_commit: Option<String>,
    pub detail: String,
}

/// What `BuildVersion.g.cs` says.
#[derive(Debug, Clone, Default, PartialEq, Eq, Serialize, Deserialize)]
pub struct GamemodeVersion {
    pub version: String,
    pub commit: String,
    pub build_date: String,
}

/// Local and remote git tips.
#[derive(Debug, Clone, Default, PartialEq, Eq, Serialize, Deserialize)]
pub struct GitVersion {
    pub head: String,
    pub branch: Option<String>,
    pub describe: Option<String>,
    pub dirty: bool,
    pub remote_head: Option<String>,
}

impl GitVersion {
    /// The remote is somewhere this checkout is not.
    ///
    /// Deliberately not "behind" in the ancestry sense: answering that needs a
    /// fetch, and a probe that mutates the operator's working tree on a timer is
    /// a probe that will eventually surprise somebody.
    pub fn is_behind(&self) -> bool {
        match &self.remote_head {
            Some(remote) => !remote.is_empty() && *remote != self.head,
            None => false,
        }
    }

    pub fn short_head(&self) -> &str {
        &self.head[..self.head.len().min(8)]
    }
}

/// Installed against published build ids for the dedicated server.
#[derive(Debug, Clone, Default, PartialEq, Eq, Serialize, Deserialize)]
pub struct EngineVersion {
    pub installed_build: String,
    pub available_build: Option<String>,
    /// What the engine's own `version` console command printed, when one has run.
    pub reported: Option<String>,
}

impl EngineVersion {
    pub fn is_behind(&self) -> bool {
        match &self.available_build {
            Some(available) => !available.is_empty() && *available != self.installed_build,
            None => false,
        }
    }
}

/// Where to look for each answer.
#[derive(Debug, Clone)]
pub struct Probe {
    /// The `.sbproj` directory, holding `Code/Core/BuildVersion.g.cs`.
    pub project_dir: PathBuf,
    /// The steam install directory, holding `steamapps/`.
    pub steam_dir: Option<PathBuf>,
    /// `steamcmd`, when it is on this machine.
    pub steamcmd: Option<PathBuf>,
    /// Whether to ask the git remote. Off makes every probe local and offline.
    pub check_remote: bool,
}

/// Run every probe that can answer.
///
/// Never fails as a whole: an unavailable answer becomes a line in `problems`,
/// because "the updater could not reach github" must not stop the dashboard
/// rendering the versions it does know.
pub async fn probe(probe: &Probe) -> Versions {
    let mut versions = Versions::default();

    match read_build_version(&probe.project_dir) {
        Ok(Some(stamp)) => versions.gamemode = Some(stamp),
        Ok(None) => versions
            .problems
            .push("no Code/Core/BuildVersion.g.cs; the gamemode version is unknown".to_owned()),
        Err(why) => versions.problems.push(why),
    }

    match git_version(&probe.project_dir, probe.check_remote).await {
        Ok(Some(git)) => versions.git = Some(git),
        Ok(None) => {}
        Err(why) => versions.problems.push(why),
    }

    match engine_version(probe).await {
        Ok(Some(engine)) => versions.engine = Some(engine),
        Ok(None) => {}
        Err(why) => versions.problems.push(why),
    }

    versions
}

/// Parse the three constants out of the generated C# file.
///
/// Reading the generated source rather than running anything: it is committed,
/// it is what the build reports in-game, and it works inside a container that
/// has neither git nor a dotnet SDK.
pub fn read_build_version(project_dir: &Path) -> Result<Option<GamemodeVersion>, String> {
    let path = project_dir
        .join("Code")
        .join("Core")
        .join("BuildVersion.g.cs");
    if !path.exists() {
        return Ok(None);
    }

    // The file is written CRLF by `stamp_version.py`; read as bytes so the line
    // endings are not rewritten on the way in.
    let bytes =
        std::fs::read(&path).map_err(|e| format!("could not read {}: {e}", path.display()))?;
    let text = String::from_utf8_lossy(&bytes);

    Ok(Some(GamemodeVersion {
        version: constant(&text, "Version").unwrap_or_default(),
        commit: constant(&text, "Commit").unwrap_or_default(),
        build_date: constant(&text, "BuildDate").unwrap_or_default(),
    }))
}

/// `public const string Name = "value";`
fn constant(source: &str, name: &str) -> Option<String> {
    let needle = format!("{name} = \"");
    let start = source.find(&needle)? + needle.len();
    let rest = &source[start..];
    let end = rest.find('"')?;
    Some(rest[..end].to_owned())
}

async fn git_version(dir: &Path, check_remote: bool) -> Result<Option<GitVersion>, String> {
    if !dir.join(".git").exists() {
        // A container image has no working tree. Not a fault.
        return Ok(None);
    }

    let head = match git(dir, &["rev-parse", "HEAD"]).await {
        Ok(head) => head,
        Err(why) => return Err(format!("git rev-parse failed: {why}")),
    };

    let branch = git(dir, &["rev-parse", "--abbrev-ref", "HEAD"]).await.ok();
    let describe = git(dir, &["describe", "--tags", "--always"]).await.ok();
    let dirty = git(dir, &["status", "--porcelain"])
        .await
        .map(|out| !out.trim().is_empty())
        .unwrap_or(false);

    let remote_head = if check_remote {
        // `ls-remote`, never `fetch`: this runs on a timer, possibly against a
        // checkout somebody is working in, and it must not write to their tree.
        let remote = match git(dir, &["ls-remote", "origin", "refs/heads/main"]).await {
            Ok(output) => Ok(output),
            Err(_) => git(dir, &["ls-remote", "origin", "HEAD"]).await,
        };
        match remote {
            Ok(output) => output
                .split_whitespace()
                .next()
                .map(str::to_owned)
                .filter(|hash| hash.len() >= 7),
            Err(_) => None,
        }
    } else {
        None
    };

    Ok(Some(GitVersion {
        head,
        branch: branch.filter(|b| b != "HEAD"),
        describe,
        dirty,
        remote_head,
    }))
}

async fn git(dir: &Path, args: &[&str]) -> Result<String, String> {
    let output = tokio::process::Command::new("git")
        .arg("-C")
        .arg(dir)
        .args(args)
        .stdin(Stdio::null())
        .output()
        .await
        .map_err(|e| e.to_string())?;

    if !output.status.success() {
        return Err(String::from_utf8_lossy(&output.stderr).trim().to_owned());
    }

    Ok(String::from_utf8_lossy(&output.stdout).trim().to_owned())
}

async fn engine_version(probe: &Probe) -> Result<Option<EngineVersion>, String> {
    let Some(steam_dir) = &probe.steam_dir else {
        return Ok(None);
    };

    let manifest = steam_dir
        .join("steamapps")
        .join(format!("appmanifest_{SBOX_DEDICATED_APP_ID}.acf"));

    if !manifest.exists() {
        return Ok(None);
    }

    let text = std::fs::read_to_string(&manifest)
        .map_err(|e| format!("could not read {}: {e}", manifest.display()))?;

    let installed = acf_value(&text, "buildid")
        .ok_or_else(|| format!("{} has no buildid", manifest.display()))?;

    let available = match &probe.steamcmd {
        Some(steamcmd) => published_build(steamcmd).await.ok().flatten(),
        None => None,
    };

    Ok(Some(EngineVersion {
        installed_build: installed,
        available_build: available,
        reported: None,
    }))
}

/// Ask Steam what the public branch currently publishes.
///
/// `app_info_print` needs a login even for an anonymous app, and it prints a
/// VDF tree rather than anything structured, so this reads the `public` branch's
/// `buildid` out of it by shape.
async fn published_build(steamcmd: &Path) -> Result<Option<String>, String> {
    let output = tokio::process::Command::new(steamcmd)
        .args([
            "+@ShutdownOnFailedCommand",
            "1",
            "+@NoPromptForPassword",
            "1",
            "+login",
            "anonymous",
            "+app_info_update",
            "1",
            "+app_info_print",
            SBOX_DEDICATED_APP_ID,
            "+quit",
        ])
        .stdin(Stdio::null())
        .output()
        .await
        .map_err(|e| e.to_string())?;

    let text = String::from_utf8_lossy(&output.stdout);
    Ok(public_branch_build(&text))
}

/// Pull `branches { public { buildid "1234" } }` out of a VDF dump.
pub fn public_branch_build(vdf: &str) -> Option<String> {
    let branches = vdf.find("\"branches\"")?;
    let rest = &vdf[branches..];
    let public = rest.find("\"public\"")?;
    let rest = &rest[public..];

    let key = rest.find("\"buildid\"")? + "\"buildid\"".len();
    let after = &rest[key..];
    let open = after.find('"')? + 1;
    let value = &after[open..];
    let close = value.find('"')?;

    let build = value[..close].trim().to_owned();
    (!build.is_empty()).then_some(build)
}

/// Read a top-level `"key"  "value"` pair out of an ACF manifest.
pub fn acf_value(acf: &str, key: &str) -> Option<String> {
    let needle = format!("\"{key}\"");
    for line in acf.lines() {
        let trimmed = line.trim();
        if let Some(rest) = trimmed.strip_prefix(&needle) {
            let rest = rest.trim();
            let open = rest.find('"')? + 1;
            let value = &rest[open..];
            let close = value.find('"')?;
            return Some(value[..close].to_owned());
        }
    }
    None
}

#[cfg(test)]
#[allow(clippy::unwrap_used, clippy::expect_used)]
mod tests {
    use super::*;

    #[test]
    fn it_reads_the_generated_build_version() {
        let dir = tempfile::tempdir().unwrap();
        let core = dir.path().join("Code").join("Core");
        std::fs::create_dir_all(&core).unwrap();

        // CRLF, as `stamp_version.py` writes it.
        let source = "namespace Applejack.Core;\r\n\
             public static class BuildVersion\r\n{\r\n\
             \tpublic const string Version = \"Unreleased\";\r\n\
             \tpublic const string Commit = \"6521cb26\";\r\n\
             \tpublic const string BuildDate = \"2026-08-22\";\r\n}\r\n";
        std::fs::write(core.join("BuildVersion.g.cs"), source).unwrap();

        let stamp = read_build_version(dir.path()).unwrap().unwrap();
        assert_eq!(stamp.version, "Unreleased");
        assert_eq!(stamp.commit, "6521cb26");
        assert_eq!(stamp.build_date, "2026-08-22");
    }

    #[test]
    fn a_project_without_the_stamp_is_not_an_error() {
        let dir = tempfile::tempdir().unwrap();
        assert!(read_build_version(dir.path()).unwrap().is_none());
    }

    #[test]
    fn a_remote_that_matches_is_not_behind() {
        let mut git = GitVersion {
            head: "abc123def456".to_owned(),
            ..Default::default()
        };

        assert!(!git.is_behind(), "no remote known means no claim");

        git.remote_head = Some("abc123def456".to_owned());
        assert!(!git.is_behind());

        git.remote_head = Some("999999999999".to_owned());
        assert!(git.is_behind());
    }

    #[test]
    fn a_short_head_is_short_and_never_panics_on_a_short_hash() {
        let git = GitVersion {
            head: "abc".to_owned(),
            ..Default::default()
        };
        assert_eq!(git.short_head(), "abc");

        let git = GitVersion {
            head: "abcdef1234567890".to_owned(),
            ..Default::default()
        };
        assert_eq!(git.short_head(), "abcdef12");
    }

    #[test]
    fn an_engine_is_behind_only_when_a_different_build_is_published() {
        let mut engine = EngineVersion {
            installed_build: "19551234".to_owned(),
            available_build: None,
            reported: None,
        };
        assert!(!engine.is_behind());

        engine.available_build = Some("19551234".to_owned());
        assert!(!engine.is_behind());

        engine.available_build = Some("19559999".to_owned());
        assert!(engine.is_behind());
    }

    #[test]
    fn it_reads_a_build_id_out_of_an_acf_manifest() {
        let acf = "\"AppState\"\n{\n\t\"appid\"\t\t\"1892930\"\n\t\"buildid\"\t\t\"19551234\"\n\t\"name\"\t\t\"s&box\"\n}\n";
        assert_eq!(acf_value(acf, "buildid").as_deref(), Some("19551234"));
        assert_eq!(acf_value(acf, "appid").as_deref(), Some("1892930"));
        assert!(acf_value(acf, "absent").is_none());
    }

    #[test]
    fn it_reads_the_public_branch_build_out_of_a_vdf_dump() {
        let vdf = r#"
"1892930"
{
    "common" { "name" "s&box Dedicated Server" }
    "depots"
    {
        "branches"
        {
            "public"
            {
                "buildid"  "19559999"
                "timeupdated"  "1755000000"
            }
            "beta"
            {
                "buildid"  "19560000"
            }
        }
    }
}
"#;
        assert_eq!(public_branch_build(vdf).as_deref(), Some("19559999"));
    }

    #[test]
    fn a_vdf_without_branches_answers_nothing_rather_than_guessing() {
        assert!(public_branch_build("").is_none());
        assert!(public_branch_build("\"branches\" { }").is_none());
    }

    #[test]
    fn the_summary_says_when_an_update_is_available() {
        let versions = Versions {
            gamemode: Some(GamemodeVersion {
                version: "Unreleased".into(),
                commit: "6521cb26".into(),
                build_date: "2026-08-22".into(),
            }),
            engine: Some(EngineVersion {
                installed_build: "19551234".into(),
                available_build: Some("19559999".into()),
                reported: None,
            }),
            git: None,
            problems: Vec::new(),
        };

        assert!(versions.update_available());
        assert!(versions.summary().contains("update available"));
    }

    #[test]
    fn build_drift_matches_abbreviated_build_stamps() {
        let versions = Versions {
            gamemode: Some(GamemodeVersion {
                commit: "6521cb26".into(),
                ..Default::default()
            }),
            git: Some(GitVersion {
                head: "6521cb26abcdef".into(),
                remote_head: Some("6521cb26abcdef".into()),
                ..Default::default()
            }),
            ..Default::default()
        };
        assert_eq!(versions.build_drift().state, "synced");
    }

    #[test]
    fn build_drift_reports_a_running_build_that_differs_from_main() {
        let versions = Versions {
            gamemode: Some(GamemodeVersion {
                commit: "1111111".into(),
                ..Default::default()
            }),
            git: Some(GitVersion {
                head: "2222222".into(),
                remote_head: Some("3333333".into()),
                ..Default::default()
            }),
            ..Default::default()
        };
        assert_eq!(versions.build_drift().state, "drifted");
    }

    #[tokio::test]
    async fn probing_a_directory_that_is_not_a_checkout_is_quiet() {
        let dir = tempfile::tempdir().unwrap();
        let versions = probe(&Probe {
            project_dir: dir.path().to_path_buf(),
            steam_dir: None,
            steamcmd: None,
            check_remote: false,
        })
        .await;

        assert!(versions.git.is_none());
        assert!(versions.engine.is_none());
        assert!(!versions.update_available());
    }

    /// Against this repository, which is a real checkout.
    #[tokio::test]
    async fn it_reads_this_working_tree() {
        let here = std::env::current_dir().unwrap();
        let Ok(Some(git)) = git_version(&here, false).await else {
            eprintln!("skipping: not run from a git checkout");
            return;
        };

        assert_eq!(git.head.len(), 40, "a full sha");
        assert!(git.remote_head.is_none(), "the remote was not asked");
    }
}
